# Practical 10

**Aim:** Demonstrate NumPy array creation, indexing, slicing, reshaping, broadcasting and mathematical operations on multidimensional arrays.

### 1. Array Creation

In [1]:
import numpy as np

num_1d = np.array([7, 14, 21, 28, 35])
num_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("1D Array:", num_1d)
print("2D Array:\n", num_2d)

print("Zeros (3x4):\n", np.zeros((3, 4)))
print("Ones (2x3):\n", np.ones((2, 3)))
print("Arange (1 to 15, step 3):", np.arange(1, 16, 3))
print("Linspace (5 to 25, 5 values):", np.linspace(5, 25, 5))
print("Identity (3x3):\n", np.eye(3))

1D Array: [ 7 14 21 28 35]
2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Zeros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]
Arange (1 to 15, step 3): [ 1  4  7 10 13]
Linspace (5 to 25, 5 values): [ 5. 10. 15. 20. 25.]
Identity (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2. Indexing and Slicing

In [2]:
items = np.array([101, 102, 103, 104, 105, 106])
print("Item at 4:", items[4])
print("Items 1 to 5:", items[1:5])
print("Reversed:", items[::-1])

grid2d = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print("\n2D Grid:\n", grid2d)
print("Element (0, 2):", grid2d[0, 2])
print("Bottom 2 rows, Right 2 cols:\n", grid2d[1:, 1:])
print("First Row:", grid2d[0, :])

Item at 4: 105
Items 1 to 5: [102 103 104 105]
Reversed: [106 105 104 103 102 101]

2D Grid:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Element (0, 2): 6
Bottom 2 rows, Right 2 cols:
 [[10 12]
 [16 18]]
First Row: [2 4 6]


### 3. Array Reshape

In [3]:
series = np.arange(1, 13)
print("1D Array:", series)

matrix_2x6 = series.reshape(2, 6)
print("Reshaped 2x6:\n", matrix_2x6)

print("Flattened Array:", matrix_2x6.flatten())

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


### 4. Broadcasting Operations

In [4]:
A = np.array([[10, 20], [30, 40]])
B = np.array([5, 15])

print("Matrix A:\n", A)
print("Vector B:", B)
print("A + B:\n", A + B)
print("A ** 2 (Square):\n", A ** 2)

Matrix A:
 [[10 20]
 [30 40]]
Vector B: [ 5 15]
A + B:
 [[15 35]
 [35 55]]
A ** 2 (Square):
 [[ 100  400]
 [ 900 1600]]


### 5. Array Mathematical Operations

In [5]:
X = np.array([[5, 2], [3, 4]])
Y = np.array([[1, 2], [3, 1]])

print("Addition (X + Y):\n", X + Y)
print("Element-wise Multiply:\n", X * Y)
print("Dot Product (X @ Y):\n", X @ Y)

print("Overall Sum:", X.sum())
print("Col-wise Max:", X.max(axis=0))
print("Row-wise Min:", X.min(axis=1))
print("Mean:", X.mean())
print("Variance:", round(X.var(), 2))

Addition (X + Y):
 [[6 4]
 [6 5]]
Element-wise Multiply:
 [[5 4]
 [9 4]]
Dot Product (X @ Y):
 [[11 12]
 [15 10]]
Overall Sum: 14
Col-wise Max: [5 4]
Row-wise Min: [2 3]
Mean: 3.5
Variance: 1.25
